### ISSUE TITLE
PLatform for MacOS Intel

### ISSUE THREAD

**Issue by ora0600** [ifnesi/chatbot-restaurant#1]
Hi Italo,

hope you doing well. If you may add to your demo readme , that when you run macOS Intel like me, you need to run the demo with linux/amd64 set in PLATFORM variable. ARM64 failed.

Thank you

**Comment by ifnesi** [comment]
Hi @ora0600, great stuff, thank you very much. I have updated the readme to mention that. Thank you and I hope the demo was useful. For some reason GroqCloud hasn't worked well for the past weeks for me so I am using OpenAI whenever I need to do any demo.

**Comment by ora0600** [comment]
Yes, it is pretty nice.
